### PR TITLE
feat: more specific types

### PR DESCRIPTION
**Pull request by gf3**
Add more specific types for better TypeScript integration

### CODE REVIEW

**Comment by gf3** [comment]
@xeewi the current types break TypeScript compilation:

```
error TS2306: File '/app/node_modules/.pnpm/firebase-scrypt@2.0.0/node_modules/firebase-scrypt/dist/firebaseScrypt.d.ts' is not a module.
```

**Comment by xeewi** [comment]
Sorry for the delay, been really busy last week.

**Comment by xeewi** [comment]
It has been published to npm too, v2.1.0 

Thanks for your contribution and sorry again for the delay :)

**Comment by gf3** [comment]
no worries! thanks!

**Pull request merged**
