### PR TITLE
pure nodejs implementation

### PR DESCRIPTION
**Pull request by terite**
This should improve compatibility since it only requires scrypt and aes (node 10+), and not apt/buildtools/sudo/openssl/etc

Lint passes, tests pass.

Edit: I'm noticing that I see forward slashes `/` in the output of master and my branch, but `_` in the output of Firebase exports.

Edit 2: wasn't an issue in my code. Firebase uses a slightly different base64 algorithm between the `listUsers` api and the `auth:export` command.

### CODE REVIEW

**Comment by xeewi** [comment]
Such a nice PR ! 
Thanks a lot for the contribution !

I'm not sure to understand what you talking about in your edit ? 
You talking about the hash output when hashing a password ?

**Comment by terite** [comment]
I noticed that when I look at the output of your code and my code it has `/` where there are `_` in the hashes I download from firebase. I'm not yet sure it's the issue is in my pr or our downloads

**Comment by xeewi** [comment]
Do you have download the hash from Firebase Tools CLI with the command `auth:export` ?

**Comment by terite** [comment]
@xeewi This PR is be good to go.

In my testing I was using the results of `listUsers()`, where I should have used the `auth:export` command. The two have slightly different formats for `passwordHash` and `salt`.

https://github.com/firebase/firebase-tools/blob/master/src/accountExporter.js#L42

**Comment by xeewi** [comment]
Yes it's on the reamed.md ahah
There is a warning section about that
Maybe I should try to make it more visible ! 

Thanks for your PR ! I merge it and release it in the hour !

**Review by xeewi — APPROVED** [review]
:rocket: :tada:

**Comment by xeewi** [comment]
Oh yeah, it's gonna be v2 now, because it's a so huge change ! 
Thanks a lot again, it's really nice ! 

Edit : It's published, you can update your package.json

**Pull request merged**
